export const FIRST_IMAGES = [
  'assets/background/botera/1.jpg',
//   'assets/background/botera/2.jpg',
//   'assets/background/botera/3.jpg',
//   'assets/background/botera/4.jpg',
  'assets/background/colonia/1.jpg',
//   'assets/background/colonia/2.jpg',
//   'assets/background/colonia/3.jpg',
//   'assets/background/colonia/4.jpg',
  'assets/background/covid/1.jpg',
  'assets/background/fogones/1.jpg',
//   'assets/background/fogones/2.jpg',
//   'assets/background/fogones/3.jpg',
  'assets/background/futbol/1.jpg',
//   'assets/background/futbol/2.jpg',
//   'assets/background/futbol/3.jpg',
//   'assets/background/futbol/4.jpg',
  'assets/background/historia/1.jpg',
  'assets/background/hockey/1.jpg',
//   'assets/background/hockey/2.jpg',
//   'assets/background/hockey/3.jpg',
//   'assets/background/hockey/4.jpg',
  'assets/background/pileta/1.jpg',
//   'assets/background/pileta/2.jpg',
//   'assets/background/pileta/3.jpg',
//   'assets/background/pileta/4.jpg',
  'assets/background/salon/1.jpg',
//   'assets/background/salon/2.jpg',
//   'assets/background/salon/3.jpg',
//   'assets/background/salon/4.jpg',
//   'assets/background/salon/5.jpg',
  'assets/background/sede-social/1.jpg',
  'assets/background/tenis/1.jpg',
//   'assets/background/tenis/2.jpg',
//   'assets/background/tenis/3.jpg',
];
